# Generated by Django 4.2.6 on 2025-02-24 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_group', models.CharField(max_length=100)),
                ('course_code', models.CharField(max_length=50, unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('scu', models.IntegerField()),
                ('is_core', models.BooleanField()),
                ('passing_grade', models.CharField(blank=True, default='NA', max_length=2, null=True)),
                ('prerequisites', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_no', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('max_scu', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_method', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.course')),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.learningobjective')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.semester')),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.semester')),
            ],
            options={
                'unique_together': {('semester', 'course')},
            },
        ),
    ]
