# Generated by Django 4.2.6 on 2025-02-13 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='passing_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
