# Generated by Django 4.2.6 on 2025-02-17 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog_app', '0002_alter_course_passing_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_method', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.course')),
                ('learning_objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.learningobjective')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_catalog_app.semester')),
            ],
        ),
    ]
