# Generated by Django 4.2.6 on 2025-02-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_catalog_app', '0004_alter_course_passing_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='passing_grade',
            field=models.CharField(blank=True, default='NA', max_length=2, null=True),
        ),
    ]
